### ISSUE TITLE
selects data

### ISSUE THREAD

**Issue by atherdon** [atherdon/recipe-search-react#2]
@rahuldcoder please check this file: https://github.com/atherdon/recipe-api-only/blob/master/bin/import2/ingredients.js

https://github.com/atherdon/recipe-api-only/blob/master/bin/allergy.js

https://github.com/atherdon/recipe-api-only/blob/master/bin/courses.js

https://github.com/atherdon/recipe-api-only/blob/master/bin/cuisine.js

https://github.com/atherdon/recipe-api-only/blob/master/bin/diet.js

https://github.com/atherdon/recipe-api-only/blob/master/bin/holidays.js

**Comment by atherdon** [comment]
@rahuldcoder i think we can close this issue, right?

**Comment by rahuldcoder** [comment]
ya sure.
