### ISSUE TITLE
update project structure. move files from folder 'recipe' into repository root.

### ISSUE THREAD

**Issue by atherdon** [atherdon/recipe-search-react#8]
I want to enable autochecking dependencies, and this will be awesome to have an updated
  
![image](https://user-images.githubusercontent.com/1469198/34652242-afb3a19a-f3ec-11e7-9109-4d71662be823.png)

**Comment by rahuldcoder** [comment]
The repository structure has been updated. I think we can close this issue.

**Comment by atherdon** [comment]
dependablebot enabled
